apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ai_governance
    user: aigovuser
    secureJsonData:
      password: aigovpass
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
